name: CMake with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-9 lcov

    - name: Configure CMake
      working-directory: ./_build
      run: |
        mkdir -p _build
        CXX=/usr/bin/g++-9 cmake -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
        
    - name: Build
      working-directory: ./_build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Run tests
      working-directory: ./_build
      run: ./RunTest

    - name: Generate coverage report
      working-directory: ./_build
      run: |
        lcov --version
        lcov --rc lcov_branch_coverage=1 --capture --directory . --output-file coverage.info
        lcov --rc lcov_branch_coverage=1 --remove coverage.info '/usr/*' '*/gtest/*' '*/gmock/*' --output-file filtered_coverage.info
        genhtml --rc genhtml_branch_coverage=1 filtered_coverage.info --output-directory coverage_report

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: _build/coverage_report
