name: CMake with Coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-9 lcov

    - name: Create build directory
      run: mkdir -p _build

    - name: Configure CMake
      working-directory: _build
      run: |
        CXX=/usr/bin/g++-9 cmake -DCOVERAGE=1 -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} ..
        
    - name: Build
      working-directory: _build
      run: cmake --build . --config ${{env.BUILD_TYPE}}

    - name: Run tests
      working-directory: _build
      run: ./RunTest

    - name: Generate coverage
      working-directory: _build
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/gtest/*' '*/gmock/*' --output-file filtered_coverage.info
        genhtml filtered_coverage.info --output-directory coverage_report

    - name: Upload coverage
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: _build/coverage_report
